### ISSUE TITLE
Todo List of Features

### ISSUE THREAD

**Issue by Artezi0** [Artezi0/notebucket#1]
# Todo List

- [ ] Add media querry 
- [ ] Drag and drop list arrangement
- [ ] GIF and image support
